version: 2

build:
    image: testing

sphinx:
    configuration: docs/source/conf.py

conda:
    environment: tests/docker/environment.yml

python:
    version: 3.9
    install:
        - requirements: docs/requirements.txt
        - method: pip
          path: .
