version: 2

build:
    image: testing

sphinx:
    configuration: docs/source/conf.py

conda:
    environment: tests/docker/environment.yml

python:
    install:
        - method: pip
          path: .
