version: 2

sphinx:
    configuration: docs/source/conf.py

build:
    os: ubuntu-lts-latest
    tools:
        python: "3.13"
    jobs:
        pre_create_environment:
            - asdf plugin add uv
            - asdf install uv latest
            - asdf global uv latest
        create_environment:
            - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
        install:
            - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --extra dev
