version: 2

sphinx:
    configuration: docs/source/conf.py

python:
    install:
        - requirements: docs/requirements.txt
        - method: pip
          path: .
          extra_requirements:
            - "--no-deps"
