name: Publish release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  publish-release:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/stk-test-environment

    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install stk
        run: |
          . /deps/venv/bin/activate
          pip install --no-deps -e .
      - name: Build stk
        run: |
          . /deps/venv/bin/activate
          pip freeze --all
          ls -al src/stk
          python -m build
      - name: Publish stk
        run: >
          . /deps/venv/bin/activate

          tar xf dist/stk*.tar.gz

          ls -al .
          ls -al stk*/src/stk
          # twine upload
          # -u ${{ secrets.PYPI_USERNAME }}
          # -p ${{ secrets.PYPI_PASSWORD }}
          # dist/*
