name: Publish release
on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"
jobs:
    publish-release:
        runs-on: ubuntu-latest
        env:
            VERSION: ${{ github.ref_name }}
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v6
              with:
                  enable-cache: true
            - uses: actions/setup-python@v5
              with:
                  python-version-file: "pyproject.toml"
            - run: uv build
            - run: uv publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
