name: Run pytest

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
        - name: Git checkout
          uses: actions/checkout@v2

        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.3.0

        - name: Add conda to system path
          run: |
            # $CONDA is an environment variable pointing to the root of
            # the miniconda directory
            echo $CONDA/bin >> $GITHUB_PATH

        - name: Install dependencies
          run: |
            conda env update --name base --file tests/environment.yml

        - name: Lint with flake8
          run: |
            conda install flake8
            flake8 . \
                --count \
                --show-source \
                --max-line-length=71 \
                --statistics
        - name: Run pytest
          run: |
            pytest
